#!/bin/bash

# Warsha App - Feature-First Clean Architecture Setup Guide
# This script demonstrates the complete project structure

echo "========================================"
echo "  Warsha Project Structure"
echo "  Feature-First Clean Architecture"
echo "========================================"
echo ""

echo "📁 Project Root: warsha_app/"
echo ""

# Core Module Structure
echo "🎨 CORE MODULE (Shared Resources)"
echo "├── lib/core/"
echo "│   ├── config/"
echo "│   │   └── service_locator.dart          ← Dependency Injection Setup"
echo "│   ├── constants/"
echo "│   │   └── app_constants.dart            ← App-wide Constants"
echo "│   ├── extensions/"
echo "│   │   └── app_extensions.dart           ← Dart Extensions (String, List, etc.)"
echo "│   ├── network/"
echo "│   │   ├── api_result.dart               ← ApiResult Wrapper Class"
echo "│   │   └── dio_client.dart               ← HTTP Client Configuration"
echo "│   └── theme/"
echo "│       ├── app_colors.dart               ← Color Palette (Orange + Dark/Black)"
echo "│       ├── app_text_styles.dart          ← Typography Styles"
echo "│       └── app_theme.dart                ← Theme Configuration (Light/Dark)"
echo ""

# Feature Module Structure
echo "🏠 FEATURES (Feature-Specific Code)"
echo ""
echo "Feature Structure Pattern:"
echo "├── features/{feature_name}/"
echo "│   ├── presentation/                    ← UI Layer"
echo "│   │   ├── bloc/                        ← State Management (Events, States, Bloc)"
echo "│   │   ├── pages/                       ← Full-screen Pages"
echo "│   │   └── widgets/                     ← Reusable Widgets"
echo "│   ├── domain/                          ← Business Logic Layer"
echo "│   │   ├── entities/                    ← Business Entities"
echo "│   │   ├── repositories/                ← Repository Interfaces"
echo "│   │   └── usecases/                    ← Business Use Cases"
echo "│   └── data/                            ← Data Access Layer"
echo "│       ├── datasources/                 ← Local/Remote Data Sources"
echo "│       ├── models/                      ← JSON Serializable Models"
echo "│       └── repositories/                ← Repository Implementations"
echo ""

echo "📋 Current Features:"
echo "1. ✅ home          - Dashboard with workshops and bookings"
echo "2. ⏳ booking       - Booking creation and management"
echo ""

echo "========================================"
echo "  Technology Stack"
echo "========================================"
echo "• State Management:  Bloc/Cubit (flutter_bloc)"
echo "• Networking:        Dio (HTTP client)"
echo "• DI Container:      GetIt"
echo "• Serialization:     JSON Serializable"
echo "• Value Equality:    Equatable"
echo ""

echo "========================================"
echo "  Setup Commands"
echo "========================================"
echo ""
echo "1️⃣  Get Dependencies:"
echo "   flutter pub get"
echo ""
echo "2️⃣  Generate JSON Code:"
echo "   dart run build_runner build"
echo ""
echo "3️⃣  Run the App:"
echo "   flutter run"
echo ""
echo "4️⃣  Analyze Code:"
echo "   flutter analyze"
echo ""
echo "5️⃣  Format Code:"
echo "   dart format lib/"
echo ""

echo "========================================"
echo "  Adding a New Feature"
echo "========================================"
echo ""
echo "Step 1: Create Directory Structure"
echo "   mkdir -p lib/features/{feature}/{presentation,domain,data}"
echo ""
echo "Step 2: Create Domain Layer"
echo "   • Entity (domain/entities/)"
echo "   • Repository Interface (domain/repositories/)"
echo "   • Usecases (domain/usecases/)"
echo ""
echo "Step 3: Create Data Layer"
echo "   • Models (data/models/) - use @JsonSerializable()"
echo "   • Datasources (data/datasources/)"
echo "   • Repository Implementation (data/repositories/)"
echo ""
echo "Step 4: Create Presentation Layer"
echo "   • Events (presentation/bloc/)"
echo "   • States (presentation/bloc/)"
echo "   • Bloc (presentation/bloc/)"
echo "   • Pages (presentation/pages/)"
echo "   • Widgets (presentation/widgets/)"
echo ""
echo "Step 5: Register Dependencies"
echo "   • Update lib/core/config/service_locator.dart"
echo ""
echo "Step 6: Add to Main"
echo "   • Update MultiBlocProvider in main.dart"
echo ""

echo "========================================"
echo "  Brand Colors"
echo "========================================"
echo "🟠 Primary Orange:    #FF6B00"
echo "⬛ Dark/Charcoal:     #1A1A1A"
echo "🟫 Dark Secondary:    #2D2D2D"
echo "⚪ Light Background:  #FAFAFA"
echo ""

echo "========================================"
echo "  Project Documentation"
echo "========================================"
echo "See ARCHITECTURE.md for detailed documentation"
echo "including:"
echo "  • Architecture overview"
echo "  • Data flow diagrams"
echo "  • Step-by-step feature creation guide"
echo "  • Best practices"
echo "  • Troubleshooting"
echo ""

echo "========================================"
echo "✨ Setup Complete! Happy Coding! ✨"
echo "========================================"
